#!/usr/bin/env python3
"""Pin requirements.in to the versions currently installed -> requirements.txt.

Philosophy: install the versions you intend to ship, test them, then lock to
*exactly those* versions. This keeps the release build reproducible and the
third-party notices deterministic without resolving to untested "latest"
releases. Run it inside the environment whose versions you want to freeze:

    python scripts/lock_requirements.py

It walks the runtime dependency closure of requirements.in from installed
package metadata (no network), skips optional "extra" dependencies, and drops
backport shims that only apply to Python versions older than the build target.
Conditional platform dependencies keep their environment marker.
"""
from __future__ import annotations

import importlib.metadata as ilm
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
IN = ROOT / "requirements.in"
OUT = ROOT / "requirements.txt"

installed = {
    canonicalize_name(d.metadata["Name"]): d.version
    for d in ilm.distributions()
    if d.metadata.get("Name")
}


def direct_names() -> list[str]:
    names = []
    for line in IN.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            names.append(Requirement(line).name)
    return names


def build() -> str:
    # marker per package: None means "required unconditionally somewhere".
    marker: dict[str, str | None] = {}
    order: list[str] = []

    def visit(name: str, incoming: str | None) -> None:
        cn = canonicalize_name(name)
        first = cn not in marker
        if first:
            marker[cn] = incoming
        elif incoming is None:
            marker[cn] = None  # an unconditional edge wins
        if not first or cn not in installed:
            return
        order.append(cn)
        try:
            dist = ilm.distribution(cn)
        except ilm.PackageNotFoundError:
            return
        for req in dist.requires or []:
            r = Requirement(req)
            m = str(r.marker) if r.marker else None
            if m and "extra" in m:
                continue  # optional extras are not runtime deps
            visit(r.name, m)

    for d in direct_names():
        visit(d, None)

    lines = [
        "# GENERATED by scripts/lock_requirements.py from requirements.in.",
        "# Do not edit by hand. Pinned to the tested/installed versions; regenerate",
        "# after changing requirements.in or upgrading a dependency, then re-run",
        "# scripts/collect_notices.py and commit both.",
        "",
    ]
    for cn in sorted(x for x in order if x in installed):
        m = marker.get(cn)
        suffix = f" ; {m}" if m else ""
        lines.append(f"{cn}=={installed[cn]}{suffix}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    missing = [canonicalize_name(n) for n in direct_names() if canonicalize_name(n) not in installed]
    if missing:
        sys.exit(f"lock_requirements: not installed here: {', '.join(missing)}")
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
